---
name: security
on:
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif
          category: dependencies-analysis

  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep \
            --sarif \
            --output SourceCodeAnalysisFull.sarif \
            || true

      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysisFull.sarif
          category: source-code-analysis
